eat_fit_app/urls.py
from django.conf.urls.static import static
from django.urls import path, include, re_path
from eat_fit_app.views import RecipeListView, RecipeDetailsView, CategoryListView, RecipeAddView, \
    RecipeEditView, RecipeDeleteView, OccasionListView, MainView, \
    RecipeByCategoryView, RecipeByOccasionView, CuisineListView, RecipeByCuisineView, UserRecipeListVew,\
    IngredientAddView
from eat_fit_django_project import settings

urlpatterns = [

    path('', MainView.as_view() , name='index'),
    path('recipes/', RecipeListView.as_view(), name='recipes'),
    path('my-recipes/', UserRecipeListVew.as_view(), name='my-recipes'),
    path('recipes/<int:recipe_id>/', RecipeDetailsView.as_view(), name='recipe-details'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('recipes/category/<int:category_id>/', RecipeByCategoryView.as_view(), name='recipes-by-category'),
    path('recipes/occasion/<int:occasion_id>/', RecipeByOccasionView.as_view(), name='recipes-by-occasion'),
    path('recipes/cuisine/<int:cuisine_id>/', RecipeByCuisineView.as_view(), name='recipes-by-cuisine'),
    path('recipe/add/', RecipeAddView.as_view(), name='recipe-add'),
    path('recipe/edit/<int:recipe_id>/', RecipeEditView.as_view(), name='recipe-edit'),
    path('recipe/delete/<int:recipe_id>/', RecipeDeleteView.as_view(), name='recipe-delete'),
    path('occasions/', OccasionListView.as_view(), name='occasions'),
    path('cuisine/', CuisineListView.as_view(), name='cuisines'),
    path('add-ingredient/', IngredientAddView.as_view(),name='ingredient-add' ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

eat_fit_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from eat_fit_app.views import *
from eat_fit_django_project import settings
from image_handler.views import *
from user.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eat_fit_app.urls')),
    path('image/', include('image_handler.urls', namespace='image_handler')),
    path('user/', include('user.urls', namespace='user')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_handler/urls.py
from django.urls import path
from image_handler.views import TestView, RecipeImageUploadView, RecipeImageDeleteView

app_name = 'image_handler'

urlpatterns = [
    path('', TestView.as_view(), name='test_view'),
    path('recipe/image-upload/<int:recipe_id>/', RecipeImageUploadView.as_view(), name='recipe-image-upload'),
    path('recipe/<int:recipe_id>/delete-image/<int:image_id>/', RecipeImageDeleteView.as_view(),
         name='recipe-image-delete'),

]

user/urls.py
from django.urls import path
from .views import UserRegisterView, UserLoginView, UserLogoutView, UserEditView, UserPasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView

app_name = 'user'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('edit-profile', UserEditView.as_view(), name='edit-profile'),
    path('password-change/', UserPasswordChangeView.as_view(), name='change-password'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='user/password-change-done.html')
         , name='password_change_done'),
]

eat_fit_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Recipe(models.Model):
    name = models.CharField(max_length=128)
    recipe_ingredients = models.ManyToManyField('Ingredients', through='RecipeIngredients', related_name='recipes')
    description = models.TextField()
    instructions = models.TextField(default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='recipes')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    recipes = models.ManyToManyField(Recipe, through='RecipeCategory', related_name='categories')

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class RecipeCategory(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Recipe Categories'

    def __str__(self):
        return self.category.name


class Ingredients(models.Model):
    name = models.CharField(max_length=128)
    recipe = models.ManyToManyField(Recipe, through='RecipeIngredients', related_name='ingredients')

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Ingredients'

    def __str__(self):
        return self.name


class RecipeIngredients(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredients = models.ForeignKey(Ingredients, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    measure = models.ForeignKey('RecipeIngredientsMeasure', on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = 'Recipe Ingredients'

    def __str__(self):
        return f' Recipe: {self.recipe.name}| Ingredient: {self.ingredients.name}| Quantity: {self.quantity}'


class RecipeIngredientsMeasure(models.Model):
    measure = models.CharField(max_length=64)

    def __str__(self):
        return self.measure


class Occasion(models.Model):
    name = models.CharField(max_length=128, default='')
    description = models.TextField(max_length=128)
    recipes = models.ManyToManyField(Recipe, through='RecipeOccasion', related_name='occasions')

    class Meta:
        verbose_name_plural = 'Occasions'

    def __str__(self):
        return self.name


class RecipeOccasion(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, null=True)
    occasion = models.ForeignKey(Occasion, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = 'Recipe Occasions'

    def __str__(self):
        return self.occasion.name


class Cuisine(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    recipes = models.ManyToManyField(Recipe, through='RecipeCuisine', related_name='cuisines')

    class Meta:
        verbose_name_plural = 'Cuisines'

    def __str__(self):
        return self.name


class RecipeCuisine(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    cuisine = models.ForeignKey(Cuisine, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Recipe Cuisines'

    def __str__(self):
        return self.cuisine.name

user/models.py
from django.db import models

# Create your models here.

eat_fit_app/views.py
import json

from django.shortcuts import render, redirect, get_object_or_404

from django.views import View
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from eat_fit_app.forms import RecipeForm, RecipeIngredientFormSet, IngredientForm
from eat_fit_app.models import Recipe, Category, Occasion, Cuisine, RecipeCategory, RecipeOccasion, RecipeCuisine, \
    Ingredients, RecipeIngredientsMeasure
import logging

logger = logging.getLogger(__name__)


class MainView(View):
    def get(self, request):
        return render(request, "index.html")


# class RecipeListView(View):
#
#     def get(self, request):
#         recipes = Recipe.objects.prefetch_related('recipe_images').all()
#
#         for recipe in recipes:
#             main_image = recipe.recipe_images.filter(type='main_image').first()
#             recipe.main_image_url = main_image.image_file.url if main_image else None
#
#         return render(request, "app-recipes.html", {"recipes": recipes})


class RecipeListView(ListView):
    model = Recipe
    paginate_by = 10
    template_name = 'app-recipes.html'
    context_object_name = 'recipes'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipes = context['recipes']
        for recipe in recipes:
            main_image = recipe.recipe_images.filter(type='main_image').first()
            recipe.main_image_url = main_image.image_file.url if main_image else None
        return context


class RecipeDetailsView(View):
    def get(self, request, recipe_id):
        recipe = get_object_or_404(Recipe, id=recipe_id)
        main_image = recipe.recipe_images.filter(type='main_image').first()
        additional_images = recipe.recipe_images.filter(type='additional_image').all()

        context = {
            'recipe': recipe,
            'main_image': main_image,
            'additional_images': additional_images,
            'ingredients': recipe.recipeingredients_set.all(),
            'categories': recipe.categories.all(),
            'occasions': recipe.occasions.all(),
            'cuisines': recipe.cuisines.all(),
        }
        return render(request, "app-recipe-details.html", context)


class UserRecipeListVew(LoginRequiredMixin, View):
    def get(self, request):
        user_recipes = Recipe.objects.filter(user=request.user).prefetch_related('recipe_images')

        for recipe in user_recipes:
            main_image = recipe.recipe_images.filter(type='main_image').first()
            recipe.main_image_url = main_image.image_file.url if main_image else None
        return render(request, "user-recipes.html", {"recipes": user_recipes})


class CategoryListView(View):
    def get(self, request):
        categories = Category.objects.all()
        return render(request, "app-categories.html", {"categories": categories})


class RecipeByCategoryView(View):
    def get(self, request, category_id):
        category = Category.objects.get(id=category_id)
        recipes = Recipe.objects.filter(categories=category)
        return render(request, "app-recipes.html", {"recipes": recipes})


class RecipeByOccasionView(View):
    def get(self, request, occasion_id):
        occasion = Occasion.objects.get(id=occasion_id)
        recipes = Recipe.objects.filter(occasions=occasion)
        return render(request, "app-recipes.html", {"recipes": recipes})


class RecipeByCuisineView(View):

    def get(self, request, cuisine_id):
        cuisine = Cuisine.objects.get(id=cuisine_id)
        recipes = Recipe.objects.filter(cuisines=cuisine)
        return render(request, "app-recipes.html", {"recipes": recipes})


class RecipeAddView(LoginRequiredMixin, View):

    def handle_no_permission(self):
        messages.info(self.request, "Please login to add a recipe")
        return super().handle_no_permission()

    def get(self, request):

        form = RecipeForm()
        formset = RecipeIngredientFormSet()
        return render(request, 'app-recipe-add.html', {'form': form, 'formset': formset})

    def post(self, request):
        form = RecipeForm(request.POST)
        formset = RecipeIngredientFormSet(request.POST)

        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.user = request.user
            recipe.save()

            RecipeCategory.objects.create(recipe=recipe, category=form.cleaned_data['category'])
            RecipeOccasion.objects.create(recipe=recipe, occasion=form.cleaned_data['occasion'])
            RecipeCuisine.objects.create(recipe=recipe, cuisine=form.cleaned_data['cuisine'])

            formset.instance = recipe
            if formset.is_valid():
                formset.save()
                return redirect('recipe-details', recipe_id=recipe.id)
            else:
                print("Form errors:", formset.errors)

        if not form.is_valid():
            print("Form errors:", form.errors)

        return render(request, 'app-recipe-add.html', {'form': form, 'formset': formset})


class RecipeEditView(LoginRequiredMixin, View):

    def get(self, request, recipe_id):
        recipe = get_object_or_404(Recipe, id=recipe_id)
        form = RecipeForm(instance=recipe)
        formset = RecipeIngredientFormSet(instance=recipe)

        ingredients = list(Ingredients.objects.values('id', 'name'))
        measures = list(RecipeIngredientsMeasure.objects.values('id', 'measure'))

        if not (request.user == recipe.user or request.user.is_staff):
            messages.error(request, "You do not have permission to edit this recipe.")
            return redirect('recipe-details', recipe_id=recipe.id)

        return render(request, 'app-recipe-edit.html', {
            'form': form,
            'formset': formset,
            'recipe': recipe,
            'ingredients_json': json.dumps(ingredients),
            'measures_json': json.dumps(measures),
        })

    def post(self, request, recipe_id):
        recipe = get_object_or_404(Recipe, id=recipe_id)
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        formset = RecipeIngredientFormSet(request.POST, instance=recipe)

        if not (request.user == recipe.user or request.user.is_staff):
            messages.error(request, "You do not have permission to edit this recipe.")
            return redirect('recipe-details', recipe_id=recipe.id)

        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            messages.success(request, "Recipe updated successfully.")
            return redirect('recipe-details', recipe_id=recipe.id)
        else:
            messages.error(request, "There was an error with your submission. Please check the form.")
            return render(request, 'app-recipe-edit.html', {
                'form': form,
                'formset': formset,
                'recipe': recipe,
            })


class RecipeDeleteView(LoginRequiredMixin, View):
    def get(self, request, recipe_id):
        recipe = Recipe.objects.get(id=recipe_id)
        return render(request, 'app-recipe-delete.html', {'recipe': recipe})

    def post(self, request, recipe_id):
        recipe = Recipe.objects.get(id=recipe_id)
        recipe.delete()
        return redirect('recipes')


class IngredientAddView(LoginRequiredMixin, View):
    def get(self, request):
        form = IngredientForm
        return render(request, 'app-ingredient-add.html', {'form': form})

    def post(self, request):
        form = IngredientForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Ingredient added successfully.")
            return redirect('ingredient-add')
        else:
            messages.error(request, "There was an error with your submission")
            return render(request, 'app-ingredient-add.html', {'form': form})


class OccasionListView(View):
    def get(self, request):
        occasions = Occasion.objects.all()
        return render(request, "app-occasions.html", {"occasions": occasions})


class CuisineListView(View):
    def get(self, request):
        cuisines = Cuisine.objects.all()
        return render(request, "app-cuisines.html", {"cuisines": cuisines})

user/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.views.generic import CreateView, UpdateView
from .forms import EditUserProfileForm


class UserRegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'user/register.html'
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        messages.success(self.request, "Registration successful. You can now login.")
        return super().form_valid(form)


class UserLoginView(LoginView):
    form_class = AuthenticationForm
    template_name = 'user/login.html'
    redirect_authenticated_user = True

    def form_invalid(self, form):
        if form.non_field_errors():
            messages.error(self.request, "Invalid username or password", extra_tags='danger')

        return redirect('user:login')

    def get_success_url(self):
        messages.success(self.request, "You have successfully logged in")
        return reverse_lazy('index')


class UserLogoutView(LoginRequiredMixin, LogoutView):

    def get_success_url(self):
        messages.success(self.request, "You have been successfully logged out")
        return reverse_lazy('index')

    next_page = reverse_lazy('index')


class UserEditView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = EditUserProfileForm
    template_name = 'user/edit-profile.html'
    success_url = reverse_lazy('user:edit-profile')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        super(UserEditView, self).form_valid(form)
        messages.success(self.request, 'Profile successfully updated')
        return redirect('user:edit-profile')


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'user/change-password.html'
    success_url = reverse_lazy('user:password_change_done')

    def form_valid(self, form):
        messages.success(self.request, "Your password was successfully updated!")
        return super().form_valid(form)

eat_fit_app/templates/__base__.html
{% load static %}

<!DOCTYPE html>
<html lang="en" style="height: 100%;">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>{% block title %}{% endblock title %}</title>
    {#    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">#}

    {#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"#}
    {#          rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"#}
    {#          crossorigin="anonymous">#}
    {#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"#}
    {#            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"#}
    {#            crossorigin="anonymous"></script>#}

    {% block head %}

    {% endblock head %}
</head>

<body class="bg-secondary d-flex flex-column" style="min-height: 100%;">

<div class="loadingOverlay d-flex align-items-center justify-content-center" id="loadingOverlay">
    <div class="spinner-border" role="status"></div>
</div>


{% include 'navbar.html' %}


{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}



{% block header %}

{% endblock header %}

<main class="flex-grow-1">

    {% block content %}

    {% endblock content %}
</main>


<footer class="text-center text-lg-start bg-light">
    <div class="text-center p-4 styled-text-footer">
        Author: Adam Chrzanowski
    </div>
</footer>


<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
{#<script src="{% static 'js/jquery.min.js' %}"></script>#}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


{% block javascript %}

{% endblock javascript %}
</body>

</html>

eat_fit_app/templates/app-categories.html
{% extends '__base__.html' %}
{% load static %}

{% block title %}
    Recipes by category
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card text-center">
                    <div class="card-header">
                        <h4 class="card-title">Categories</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for category in categories %}
                            <li class="list-group-item">
                                <a href="{% url 'recipes-by-category' category.id %}" class="btn btn-outline-success">{{ category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12 text-center">
                <a href="javascript:history.back();" class="btn btn-secondary">Go Back</a>
            </div>
        </div>
    </div>
{% endblock %}

eat_fit_app/templates/app-cuisines.html
{% extends '__base__.html' %}
{% block title %}
    Recipes by cuisine
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card text-center">
                    <div class="card-header">
                        <h4 class="card-title">Cuisines</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for cuisine in cuisines %}
                            <li class="list-group-item">
                                <a href="{% url 'recipes-by-cuisine' cuisine.id %}"
                                   class="btn btn-outline-success">{{ cuisine.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12 text-center">
                <a href="javascript:history.back();" class="btn btn-secondary">Go Back</a>
            </div>
        </div>
    </div>
{% endblock %}

eat_fit_app/templates/app-ingredient-add.html
{% extends '__base__.html' %}

{% block content %}
<div class="container">
    <h2>Add Ingredient</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
</div>
{% endblock %}

eat_fit_app/templates/app-occasions.html
{% extends '__base__.html' %}
{% block title %}
    Recipes by occasions
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card text-center">
                    <div class="card-header">
                        <h4 class="card-title">Occasions</h4>
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for occasion in occasions %}
                            <li class="list-group-item">
                                <a href="{% url 'recipes-by-occasion' occasion.id %}"
                                   class="btn btn-outline-success">{{ occasion.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-md-12 text-center">
                <a href="javascript:history.back();" class="btn btn-secondary">Go Back</a>
            </div>
        </div>
    </div>
{% endblock %}

eat_fit_app/templates/app-recipe-edit.html
{% extends '__base__.html' %}
{% load static %}

{% block title %}
    Edit recipe
{% endblock title %}

{% block content %}
    <div class="container">
        <h1 class="my-4">Edit Recipe</h1>
        <form method="post" id="recipe-form" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-3">
                    {{ form.name.label_tag }}
                    {{ form.name }}
                </div>
                <div class="col-md-2 mb-3">
                    {{ form.category.label_tag }}
                    <select name="category" id="id_category" class="form-control">
                        {% for category in form.category.field.queryset %}
                            <option value="{{ category.pk }}"
                                    {% if form.instance.category == category %}selected{% endif %}>
                                {{ category.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-2 mb-3">
                    {{ form.occasion.label_tag }}
                    <select name="occasion" id="id_occasion" class="form-control">
                        {% for occasion in form.occasion.field.queryset %}
                            <option value="{{ occasion.pk }}"
                                    {% if form.instance.occasion == occasion %}selected{% endif %}>
                                {{ occasion.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-2 mb-3">
                    {{ form.cuisine.label_tag }}
                    <select name="cuisine" id="id_cuisine" class="form-control">
                        {% for cuisine in form.cuisine.field.queryset %}
                            <option value="{{ cuisine.pk }}"
                                    {% if form.instance.cuisine == cuisine %}selected{% endif %}>
                                {{ cuisine.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-3">
                    {{ form.description.label_tag }}
                    {{ form.description }}
                </div>
                <div class="col-md-6 mb-3">
                    {{ form.instructions.label_tag }}
                    {{ form.instructions }}
                </div>
            </div>

            <!-- Ingredients section -->
            <div id="form-set">
                {{ formset.management_form }}
                {% for ingredient_form in formset %}
                    <div class="row mb-2 ingredient-form">
                        {{ ingredient_form.id.as_hidden }}
                        <div class="col-md-2">
                            {{ ingredient_form.ingredients.label_tag }}
                            {{ ingredient_form.ingredients }}
                        </div>
                        <div class="col-md-1">
                            {{ ingredient_form.quantity.label_tag }}
                            {{ ingredient_form.quantity }}
                        </div>
                        <div class="col-md-1">
                            {{ ingredient_form.measure.label_tag }}
                            {{ ingredient_form.measure }}
                        </div>
                        <div class="col-md-3 d-flex align-items-end">
                            <button type="button" class="remove-ingredient btn btn-danger">Remove</button>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-md-12 d-flex justify-content-between">
                    <div>
                        <button type="button" id="add-more" class="btn btn-primary">Add More Ingredients</button>
                    </div>
                    <div>
                        <a class="btn btn-primary" href="{% url 'ingredient-add' %}">Add New Ingredient to Database</a>
                    </div>
                </div>
            </div>


            <template id="ingredient-form-template">
                <div class="row mb-2 ingredient-form">
                    <div class="col-md-3">
                        <label for="id_form-__prefix__-ingredient">Ingredient</label>
                        <select id="id_form-__prefix__-ingredient" name="form-__prefix__-ingredient"
                                class="form-control">
                        </select>
                    </div>
                    <div class="col-md-2">
                        <label for="id_form-__prefix__-quantity">Quantity</label>
                        <input type="number" id="id_form-__prefix__-quantity" name="form-__prefix__-quantity"
                               class="form-control">
                    </div>
                    <div class="col-md-3">
                        <label for="id_form-__prefix__-measure">Measure</label>
                        <select id="id_form-__prefix__-measure" name="form-__prefix__-measure" class="form-control">
                        </select>
                    </div>
                    <div class="col-md-4">
                        <button type="button" class="btn btn-danger remove-ingredient-btn">Remove</button>
                    </div>
                </div>
            </template>

            <!--- Images Section --->
            <div>
                <h3 class="mt-4 mb-3">Images</h3>
                <div class="row">
                    {% for image in recipe.recipe_images.all %}
                        <div class="col-md-6 mb-4">
                            <div class="card recipe-card shadow"
                                 style="height: 100%; display: flex; flex-direction: column;">
                                <div class="card-header bg-light">
                                    <b>Image name:</b> {{ image.name|title }}
                                </div>
                                <img src="{{ image.image_file.url }}" class="card-img-top"
                                     alt="{{ image.alt_description }}" style="height: 400px; object-fit: cover;">
                                <div class="card-body" style="flex-grow: 1;">
                                    <p class="card-text"><b>Description:</b>
                                        <br>
                                        {{ image.description|linebreaksbr }}</p>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="col">
                            <p>No images uploaded for this recipe yet.</p>
                        </div>
                    {% endfor %}

                </div>
            </div>


            <div class="row mb-3">
                <div class="col-md-12">
                    <a href="{% url 'image_handler:recipe-image-upload' recipe_id=recipe.id %}" class="btn btn-success">Upload
                        Image</a>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                    <a href="javascript:history.back();" class="btn btn-secondary">Go Back</a>
                </div>
            </div>
    </div>

{% endblock content %}


{% block javascript %}

    <script src="{% static 'js/edit_ingredients.js' %}"></script>

{% endblock javascript %}
</div>