eat_fit_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from eat_fit_app.views import *
from eat_fit_django_project import settings
from image_handler.views import *
from user.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eat_fit_app.urls')),
    path('image/', include('image_handler.urls', namespace='image_handler')),
    path('user/', include('user.urls', namespace='user')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import UserRegisterView, UserLoginView, UserLogoutView, UserEditView, UserPasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView

app_name = 'user'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('edit-profile', UserEditView.as_view(), name='edit-profile'),
    path('password-change/', UserPasswordChangeView.as_view(), name='change-password'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='user/password-change-done.html')
         , name='password_change_done'),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.models import User


class EditUserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
        }

user/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.views.generic import CreateView, UpdateView
from .forms import EditUserProfileForm


class UserRegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'user/register.html'
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        messages.success(self.request, "Registration successful. You can now login.")
        return super().form_valid(form)


class UserLoginView(LoginView):
    form_class = AuthenticationForm
    template_name = 'user/login.html'
    redirect_authenticated_user = True

    def form_invalid(self, form):
        if form.non_field_errors():
            messages.error(self.request, "Invalid username or password", extra_tags='danger')

        return redirect('user:login')

    def get_success_url(self):
        messages.success(self.request, "You have successfully logged in")
        return reverse_lazy('index')


class UserLogoutView(LoginRequiredMixin, LogoutView):

    def get_success_url(self):
        messages.success(self.request, "You have been successfully logged out")
        return reverse_lazy('index')

    next_page = reverse_lazy('index')


class UserEditView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = EditUserProfileForm
    template_name = 'user/edit-profile.html'
    success_url = reverse_lazy('user:edit-profile')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        super(UserEditView, self).form_valid(form)
        messages.success(self.request, 'Profile successfully updated')
        return redirect('user:edit-profile')


class UserPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'user/change-password.html'
    success_url = reverse_lazy('user:password_change_done')

    def form_valid(self, form):
        messages.success(self.request, "Your password was successfully updated!")
        return super().form_valid(form)

user/templates/user/change-password.html
{% extends '__base__.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>Change Password</h2>
                <form method="post" class="needs-validation" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">

                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field|add_class:"form-control" }}
                            {% if field.errors %}
                                <div class="alert alert-danger">{{ field.errors.as_text }}</div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <a href="javascript:history.back();" class="btn btn-secondary me-2">Go Back</a>
                    <button type="submit" class="btn btn-danger">Change Password</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

user/templates/user/edit-profile.html
{% extends '__base__.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>Edit Profile</h2>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field|add_class:"form-control" }}
                            {% if field.errors %}
                                <div class="alert alert-danger">{{ field.errors.as_text }}</div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <div class="d-flex justify-content-between">
                        <button type="submit" class="btn btn-primary">Update Profile
                        </button>
                        <div>
                            <a href="javascript:history.back();" class="btn btn-secondary me-2">Go Back</a>
                            <a href="{% url 'user:change-password' %}" class="btn btn-danger">Change Password</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user/templates/user/login.html
{% extends '__base__.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="container mt-4">

        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>Login</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_username" class="form-label">{{ form.username.label }}</label>
                        {{ form.username|add_class:"form-control" }}
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">{{ form.password.label }}</label>
                        {{ form.password|add_class:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

user/templates/user/password-change-done.html
{% extends '__base__.html' %}

{% block content %}
    <div class="container mt-4">
        <h2>Password Changed</h2>
        <a href="{% url 'index' %}" class="btn btn-primary">Return to the homepage</a>
    </div>
{% endblock %}

user/templates/user/register.html
{% extends '__base__.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>Register</h2>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field|add_class:"form-control" }}
                            {% if field.errors %}
                                <div class="alert alert-danger">{{ field.errors.as_text }}</div>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Register</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}